[package]
name = "hyperlight-wit-macro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = """
Procedural macros to generate shared Rust type definitions from WIT component types for use with Hyperlight
"""

[lib]
name = "hyperlight_wit_macro"
proc-macro = true

[dependencies]
wasmparser = { version = "0.246.2" }
quote = { version = "1.0.45" }
proc-macro2 = { version = "1.0.106" }
syn = { version = "2.0.117" }
hyperlight-component-util = { workspace = true }
env_logger = { version = "0.11.10" }
